apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: igress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    cert-manager.io/certificate-name: "rayatdoost-de-tls"
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - rayatdoost.de
        - www.rayatdoost.de
      secretName: rayatdoost-de 
  rules:
    - host: rayatdoost.de
      http:
        paths:
          - pathType: ImplementationSpecific 
            path: /?(.*) 
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
          - pathType: ImplementationSpecific
            path: /api/?(.*) 
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000
    - host: www.rayatdoost.de
      http:
        paths:
          - pathType: ImplementationSpecific 
            path: /?(.*) 
            backend:
              service:
                name: client-cluster-ip-service
                port: 
                  number: 3000
          - pathType: ImplementationSpecific
            path: /api/?(.*) 
            backend:
              service:
                name: server-cluster-ip-service
                port: 
                  number: 5000
